services:
  evently.api:
    image: ${DOCKER_REGISTRY-}eventlyapi
    container_name: Evently.Api
    build:
      context: .
      dockerfile: src/API/Evently.Api/Dockerfile
  
  evently.database:
    image: postgres:17.5

  evently.seq:
    image: datalust/seq:2026
    container_name: Evently.Seq
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=123
    ports:
      - "5341:5341"
      - 8081:80

volumes:
  postgres_evently: